### ISSUE TITLE
Raspberry PI Zero

### ISSUE THREAD

**Issue by bskan** [dekuNukem/USB4VC#2]
Trying this initially on a Raspberry Pi Zero (non-W) which doesn't have bluetooth/wifi.

It's done it's initial set up but now it's stuck in a loop

"Disabling ERTM.....
ertm_status: cat: /sys/module/bluetooth/paramaters/disable_ertm: No such file or directory"

Is there a way I can turn this part of the script off by editing the sd card on another system?

**Comment by dekuNukem** [comment]
Hi there! Disabling ERTM is in a seperate process, and shouldnt affect the functionality of the device. Does it not work at all?

**Comment by bskan** [comment]
The green LED comes on the one board but the OLED display has no life in it. The buttons don't appear to do anything either. I've ordered myself a Pi 3b in case it's the Pi itself that's the issue.

**Comment by bskan** [comment]
Pi3b works great so I'm guessing it's a hardware fault in my Pi Zero!
