### ISSUE TITLE
No input with SGI Octane

### ISSUE THREAD

**Issue by Jenna64bit** [dekuNukem/USB4VC#4]
Hi there!

Trying this out on my Octane for PS/2 support with the IBM module. Whole set up seems happy, Octane does seem to detect that there is a keyboard, it normally gives an error if not. But, I get no input. I suspect this is because PS/2 has multiple "scan code" modes, and SGI systems are notoriously fickle and [only want a specific one (3)](https://nixdoc.net/man-pages/IRIX/man7/pckeyboard.7.html). Might there be an easy way I can add that mapping?

**Comment by dekuNukem** [comment]
Makes sense! IBM PC Protocol Card currently supports Scan set 1 and 2. Set 3 is indeed very rare, and I don't have a machine that uses it, so even if I code the firmware I'll have no way to actually test it. 

That said, I would love to add the support for it, so looks like I might need to start looking out for the rare scan code set 3 machines.

**Comment by Jenna64bit** [comment]
Ah, fair, yeah any SGI with PS/2 will use it. That's the Indy, Octane, O2, etc. I'd also be happy to test a few times. Admittedly, that would be a lot slower than doing it yourself. Thanks for the quick reply!

**Comment by dekuNukem** [comment]
I've found a IBM Infowindow data terminal for sale with the 122-key battleship model M keyboard with the RJ45 connector.

My quick research shows that it uses scan code set 3, so I might snatch it up, hopefully it works and I can work on set 3 support!

**Comment by dekuNukem** [comment]
I have added experimental PS/2 scan code set 3 support in the latest update, it seems to work with my IBM terminal, but that's the only machine I have. Feel free to try it on yours!

Make sure your [Raspberry Pi is online](https://github.com/dekuNukem/USB4VC/blob/master/getting_started.md#optional-set-up-wifi), and select `Internet Update` from the main menu.

After updating, on the second page it should show `PB 0.4.0 RPi 0.1.3`

Let me know how it goes!

**Comment by Jenna64bit** [comment]
Hey hey!! I'm happy to say it works. Both mouse & keyboard working now on my Octane from my Logitech unifying dongle.

**Comment by dekuNukem** [comment]
Glad to hear it works! Feel free to double check the key mappings are correct, and use it for a while to see how stable it is.

Let me know if you run into any issues.

**Comment by Jenna64bit** [comment]
Probably final follow up. This has been rock solid on my workstation. Good to close by me. 


Jenna Whitehouse
***@***.***

**Comment by dekuNukem** [comment]
Great! I just released a new update with even more features, make sure to check it out 😅

https://www.kickstarter.com/projects/dekunukem/usb4vc-usb-inputs-on-retro-computers/posts/3503167
